[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]

=== Decisiones tecnológicas

Se usarán las siguientes tecnologías a lo largo del desarollo del prollecto.

|===
|Tecnología | Razón
|JavaScript | Usado como lenguaje principal para el desarollo del sistema
|React | Usado para el desarrollo de la aplicación web
|Node.js | Entorno de ejecución para JavaScrip
|MongoDB |  Usado para almacenar los datos de los usuarios
|===



=== Objetivos de calidad

|===
|Objetivo de calidad | Razón
|Usabilidad | El usuario tiene que aprender a usar la aplicación fácilmente y la interfaz debería de ser intuitiva
|Robustez | El usuario espera NO encontrar errores ni bugs mientras navega por la aplicación
|Privacidad | El usuario debe sentir que sus datos van a ser usados de una manera que garantice su seguridad
|===

****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
