[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Iniciar sesión


* Inicio de sesión en la aplicación web

[plantuml,"Sequence diagram 1",png]
----
actor Usuario
participant Aplicación
participant "Login de Solid" as Login
database POD
Usuario -> Aplicación: click en iniciar sesión
Aplicación -> Login: llama a
Usuario -> Login: se logea
Login -> Aplicación: le devuelve el POD del usuario
Aplicación -> POD: pide acceso
POD -> Aplicación: le devuelve la información del usuario
Aplicación -> Usuario: le notifica el inicio de sesión
----
=== Comprar producto

* Compra de un producto en la aplicación web

[plantuml,"Sequence diagram 2",png]
----
actor Usuario
participant Aplicación
database Mongo
database POD
Usuario -> Aplicación: selecciona los productos
Aplicación-> Mongo: pide los datos de los productos
Mongo -> Aplicación: retorna los productos
Aplicación-> Usuario: muestra los datos de los productos
Usuario -> Aplicación: hace click en comprar
Aplicación-> POD: pide la dirección del usuario
POD -> Aplicación: devuelve la dirección del usuario
Aplicación-> Aplicación: calcula costes de envío
Aplicación -> Usuario: muestra el precio y pide confirmación
Usuario -> Aplicación: confirma la compra
Aplicación-> Mongo: elimina los productos del stock
Mongo -> Mongo: se actualiza la BBDD
Aplicación -> Usuario: muestra el envío del pedido
----

