[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
* ADR 1: Almacenar localizaciones en una base de datos centralizada.
- Contexto
Debemos almacenar los datos de la cuenta del usuario para validar cuando estos se logean
que es una cuenta existente y para almacenar las nuevas cuentas que los usuarios creen.
- Decisión:
Hemos decidido almacear dichos datos en una base de datos centralizada.
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
